spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: HHo00sys
    url: jdbc:mysql://localhost:3306/bloom-duck-project
server:
  port: 8000

setting:
  pageSize: 50